### ISSUE TITLE
Challengeの画像をDBに保存する

### ISSUE THREAD

**Issue by Yuya-Furusawa** [Yuya-Furusawa/quest-api#8]
カラーの画像とモノクロの画像両方を保存する

**Comment by AtsukiTak** [comment]
s3とかに保存したいね

**Comment by Yuya-Furusawa** [comment]
とりあえず個人のs3使いますわー

**Comment by AtsukiTak** [comment]
localstackっていうサービス使えばローカル環境でs3とか再現できるよ。
で、localstackの導入を #4 でやっているので見てもらえると 🙏

**Comment by Yuya-Furusawa** [comment]
見てみる！

**Comment by Yuya-Furusawa** [comment]
画像のフレーバーテキストも表示させたいからそれもやるか

**Comment by Yuya-Furusawa** [comment]
Questページのアイコン一覧に表示させるチャレンジ名とChallengeページに表示させるチャレンジ名は一般に異なりうるかも
なのでそこは区別してSBに保存するべき？

- 渋谷区（challenge.area_name）
- 渋谷区のスターバックスに行く（challenge.name）
